# Iss text ko people1-exercise.txt ke naam ki file mein save karo.

# file=open("people1-exercise.txt","w")
# file.write("rishabh - meerut\n")
# file.write("imtiyaz - delhi\n")
# file.write("nilima - cochin\n")
# file.write("rati - shimla\n")
# file.write("ayishah - delhi\n")
# file.write("raghu - shimla\n")
# file.write("naseer - kanpur\n")
# file.write("karthikeyan - delhi\n")
# file.write("salma - jaipur\n")
# file.write("pankaj - delhi\n")
# file.write("brijesh - delhi\n")
# file.write("govind - delhi\n")
# file.write("puneet - shimla\n")
# file.write("siddhi - delhi\n")
# file.write("suman - jaipur\n")
# file.write("rajeev - shimla\n")
# file.write("mohinder - delhi\n")
# file.write("rajendra - jaipur\n")
# file.write("priyanka - shimla\n")
# file.write("neela - delhi\n")
# file.write("sashi - jaipur\n")
# file.write("sarika - delhi\n")
# file.write("deepti - shimla\n")
# file.write("harshad - delhi\n")
# file.write("trishna - raipur\n")
# file.write("pradeep - jaipur\n")
# file.write("sekhar - delhi\n")
# file.write("nand - delhi\n")
# file.write("anoop - delhi\n")
# file.write("balwinder - tokyo\n")
# file.close()

# file=open("people1-exercise.txt")
# file_data=file.read()
# print(file_data)
# file.close()


